#pragma once

#include <vector>
#include <string>

std::vector<std::vector<std::string>> actorList = {
	{"Player", "Player"},
	{"unset", ""},
	{"En_Test", "Stalfos"},
	{"unset", ""},
	{"En_GirlA", "Shop Inventory Data"},
	{"unset", ""},
	{"unset", ""},
	{"En_Part", "?: En_Part"},
	{"En_Light", "Flame"},
	{"En_Door", "Wooden Door"},
	{"En_Box", "Treasure Chest"},
	{"Bg_Dy_Yoseizo", "Great Fairy"},
	{"Bg_Hidan_Firewall", "Proximity-Activated Firewall"},
	{"En_Poh", "Graveyard Poe & Composer Brothers"},
	{"En_Okuta", "Octorok"},
	{"Bg_Ydan_Sp", "Spiderweb"},
	{"En_Bom", "Bomb Field Model"},
	{"En_Wallmas", "Wallmaster"},
	{"En_Dodongo", "Dodongo"},
	{"En_Firefly", "Keese"},
	{"En_Horse", "Adult Epona"},
	{"En_Item00", "Collectible Items {Visible}"},
	{"En_Arrow", "?: En_Arrow"},
	{"unset", ""},
	{"En_Elf", "Navi & Healing Fairy"},
	{"En_Niw", "Friendly Cucco"},
	{"unset", ""},
	{"En_Tite", "Tektite"},
	{"En_Reeba", "Leever"},
	{"En_Peehat", "Peahat"},
	{"En_Butte", "Butterfly"},
	{"unset", ""},
	{"En_Insect", "Bug"},
	{"En_Fish", "Fish"},
	{"unset", ""},
	{"En_Holl", "Room Transition Plane"},
	{"En_Scene_Change", "?: En_Scene_Change"},
	{"En_Zf", "Lizalfos & Dinalfos"},
	{"En_Hata", "Flagpole"},
	{"Boss_Dodongo", "King Dodongo"},
	{"Boss_Goma", "Gohma"},
	{"En_Zl1", "Child Zelda {Cutscene 05 & 06}"},
	{"En_Viewer", "?: En_Viewer"},
	{"En_Goma", "Gohma Larva"},
	{"Bg_Pushbox", "?: Bg_Pushbox"},
	{"En_Bubble", "Shabom"},
	{"Door_Shutter", "Door Shutter"},
	{"En_Dodojr", "Baby Dodongo"},
	{"En_Bdfire", "King Dodongo's Fire"},
	{"unset", ""},
	{"En_Boom", "Boomerang Field Model"},
	{"En_Torch2", "Dark Link"},
	{"En_Bili", "Biri"},
	{"En_Tp", "Tailpasaran"},
	{"unset", ""},
	{"En_St", "Skulltula"},
	{"En_Bw", "Torch Slug"},
	{"En_A_Obj", "Directional Sign & Square Sign {Early}"},
	{"En_Eiyer", "Land Stinger"},
	{"En_River_Sound", "Sound Effects I"},
	{"En_Horse_Normal", "Generic Horse"},
	{"En_Ossan", "?: En_Ossan"},
	{"Bg_Treemouth", "Deku Tree's Jaw"},
	{"Bg_Dodoago", "Dead Dodongo's Jaw"},
	{"Bg_Hidan_Dalm", "Fire Temple Breakable Hammer Block"},
	{"Bg_Hidan_Hrock", "Fire Temple Hammer-Activated Elevator Pillar"},
	{"En_Horse_Ganon", "Ganondorf's Horse"},
	{"Bg_Hidan_Rock", "Fire Temple Fire-Powered Elevator Block"},
	{"Bg_Hidan_Rsekizou", "Fire Temple Rotating Fire Spinner"},
	{"Bg_Hidan_Sekizou", "Fire Temple Flame-Spouting Statue"},
	{"Bg_Hidan_Sima", "Fire Temple Clover Platform"},
	{"Bg_Hidan_Syoku", "Fire Temple Fire-Powered Mini-Boss Room Face Elevator"},
	{"En_Xc", "Sheik"},
	{"Bg_Hidan_Curtain", "Circle of Flames"},
	{"Bg_Spot00_Hanebasi", "Drawbridge"},
	{"En_Mb", "Moblin"},
	{"En_Bombf", "Bomb Flower"},
	{"En_Zl2", "Adult Zelda {Cutscenes}"},
	{"Bg_Hidan_Fslift", "Hookshot Elevator"},
	{"En_OE2", "Kokiri Girl {Early}"},
	{"Bg_Ydan_Hasi", "?: Bg_Ydan_Hasi"},
	{"Bg_Ydan_Maruta", "Deku Tree Spiked Log & Dropdown Ladder"},
	{"Boss_Ganondrof", "Phantom Ganon"},
	{"unset", ""},
	{"En_Am", "Armos"},
	{"En_Dekubaba", "Deku Baba"},
	{"En_M_Fire1", "Deku Nut Effect"},
	{"En_M_Thunder", "Spin Attack Effects"},
	{"Bg_Ddan_Jd", "Dodongo's Cavern Elevator Platform"},
	{"Bg_Breakwall", "Bombable Wall"},
	{"En_Jj", "Jabu-Jabu"},
	{"En_Horse_Zelda", "Zelda's Horse"},
	{"Bg_Ddan_Kd", "Dodongo's Cavern Bombable Stairs"},
	{"Door_Warp1", "Blue Warp & Rupee-Shaped Prism"},
	{"Obj_Syokudai", "Torch Stand {Generic}"},
	{"Item_B_Heart", "Heart Container"},
	{"En_Dekunuts", "Mad Scrub"},
	{"Bg_Menkuri_Kaiten", "Rotating Ring"},
	{"Bg_Menkuri_Eye", "Statue Eye Targets"},
	{"En_Vali", "Bari"},
	{"Bg_Mizu_Movebg", "?: Bg_Mizu_Movebg"},
	{"Bg_Mizu_Water", "Water Temple Water"},
	{"Arms_Hook", "Hookshot Field Model"},
	{"En_fHG", "Phantom Ganon's Horse"},
	{"Bg_Mori_Hineri", "Forest Temple Twisting Corridor"},
	{"En_Bb", "Bubble"},
	{"Bg_Toki_Hikari", "Temple of Time Window Light Rays"},
	{"En_Yukabyun", "Flying Floor Tile"},
	{"Bg_Toki_Swd", "Master Sword"},
	{"En_Fhg_Fire", "Phantom Ganon's Lightning"},
	{"Bg_Mjin", "Warp Pad & Ocarina Pedestal"},
	{"Bg_Hidan_Kousi", "Metal Bars"},
	{"Door_Toki", "Door of Time Collision Model"},
	{"Bg_Hidan_Hamstep", "Hammer-Activated Steps"},
	{"En_Bird", "Brown Bird"},
	{"unset", ""},
	{"unset", ""},
	{"unset", ""},
	{"unset", ""},
	{"En_Wood02", "Trees & Bushes"},
	{"unset", ""},
	{"unset", ""},
	{"unset", ""},
	{"unset", ""},
	{"En_Lightbox", "Grey Rectangular Block"},
	{"En_Pu_box", "Grey Rectangular Stone Block"},
	{"unset", ""},
	{"unset", ""},
	{"En_Trap", "Blade Trap"},
	{"En_Arow_Trap", "Arrow-Deflecting Trap"},
	{"En_Vase", "Orange Pot"},
	{"unset", ""},
	{"En_Ta", "Talon"},
	{"En_Tk", "Dampé"},
	{"Bg_Mori_Bigst", "Forest Temple Bow Room Platform"},
	{"Bg_Mori_Elevator", "Forest Temple Sun Elevator"},
	{"Bg_Mori_Kaitenkabe", "Forest Temple Rotating Pre-Boss Room"},
	{"Bg_Mori_Rakkatenjo", "Forest Temple Collapsing Checkerboard Ceiling"},
	{"En_Vm", "Beamos"},
	{"Demo_Effect", "?: Demo_Effect"},
	{"Demo_Kankyo", "?: Demo_Kankyo"},
	{"Bg_Hidan_Fwbig", "Fire Temple Big Fire Wall"},
	{"En_Floormas", "Floormaster"},
	{"En_Heishi1", "Soldier {Castle Hedge Maze}"},
	{"En_Rd", "Redead & Gibdo"},
	{"En_Po_Sisters", "?: En_Po_Sisters"},
	{"Bg_Heavy_Block", "Golden Gauntlets Rock"},
	{"Bg_Po_Event", "?: Bg_Po_Event"},
	{"Obj_Mure", "Group of Bugs / Fish / Butterflies"},
	{"En_Sw", "Skullwalltula"},
	{"Boss_Fd", "Volvagia {Flying}"},
	{"Object_Kankyo", "?: Object_Kankyo"},
	{"En_Du", "Darunia"},
	{"En_Fd", "Flare Dancer"},
	{"En_Horse_Link_Child", "Child Epona"},
	{"Door_Ana", "Grotto Hole"},
	{"Bg_Spot02_Objects", "Graveyard Objects"},
	{"Bg_Haka", "Gravestone"},
	{"Magic_Wind", "Farore's Wind Effect"},
	{"Magic_Fire", "Din's Fire Effect"},
	{"unset", ""},
	{"En_Ru1", "Child Ruto"},
	{"Boss_Fd2", "Volvagia {Whack-a-Mole}"},
	{"En_Fd_Fire", "Flare Dancer's Fireball"},
	{"En_Dh", "Dead Hand"},
	{"En_Dha", "Dead Hand's Hands"},
	{"En_Rl", "Rauru"},
	{"En_Encount1", "Enemy Spawner"},
	{"Demo_Du", "Darunia"},
	{"Demo_Im", "Impa"},
	{"Demo_Tre_Lgt", "Treasure Chest Glow"},
	{"En_Fw", "Flare Dancer Core"},
	{"Bg_Vb_Sima", "Volvagia's Sinking Platform"},
	{"En_Vb_Ball", "Volvagia's Rock Attack"},
	{"Bg_Haka_Megane", "?: Bg_Haka_Megane"},
	{"Bg_Haka_MeganeBG", "Invisible Wall"},
	{"Bg_Haka_Ship", "Charon's Boat"},
	{"Bg_Haka_Sgami", "Spinning Scythes"},
	{"unset", ""},
	{"En_Heishi2", "Soldier {Castle Gate / Zelda's Courtyard / Kakariko Village}"},
	{"En_Encount2", "Falling Boulder Spawner"},
	{"En_Fire_Rock", "Flaming Debris"},
	{"En_Brob", "Stunnable Jelly Platform"},
	{"Mir_Ray", "Reflectable Ray of Light"},
	{"Bg_Spot09_Obj", "Gerudo Valley Objects"},
	{"Bg_Spot18_Obj", "Goron City Objects"},
	{"Boss_Va", "Barinade"},
	{"Bg_Haka_Tubo", "Shadow Temple Flaming Skull Vase"},
	{"Bg_Haka_Trap", "Shadow Temple Guillotine"},
	{"Bg_Haka_Huta", "Shadow Temple Coffin Lid"},
	{"Bg_Haka_Zou", "?: Bg_Haka_Zou"},
	{"Bg_Spot17_Funen", "Death Mountain Crater Smoke Plume"},
	{"En_Syateki_Itm", "Shooting Gallery Items"},
	{"En_Syateki_Man", "Shooting Gallery Proprietor"},
	{"En_Tana", "Shop Shelves"},
	{"En_Nb", "Nabooru"},
	{"Boss_Mo", "Morpha"},
	{"En_Sb", "Shellblade"},
	{"En_Bigokuta", "Big Octorok"},
	{"En_Karebaba", "Wilted Deku Baba"},
	{"Bg_Bdan_Objects", "Inside Jabu-Jabu's Belly Objects"},
	{"Demo_Sa", "Saria {Cutscenes}"},
	{"Demo_Go", "Generic Goron {Cutscenes}"},
	{"En_In", "Ingo"},
	{"En_Tr", "Kotake & Koume"},
	{"Bg_Spot16_Bombstone", "Dodongo's Cavern Boulder Blockade"},
	{"unset", ""},
	{"Bg_Hidan_Kowarerukabe", "Bombable Wall & Cracked Floor {Fire Temple}"},
	{"Bg_Bombwall", "Bombable Wall {Death Mountain Trail}"},
	{"Bg_Spot08_Iceblock", "Drifting Ice Platform"},
	{"En_Ru2", "Adult Ruto"},
	{"Obj_Dekujr", "Deku Tree Sprout"},
	{"Bg_Mizu_Uzu", "Water Current"},
	{"Bg_Spot06_Objects", "Lake Hylia Objects"},
	{"Bg_Ice_Objects", "Ice Cavern Objects"},
	{"Bg_Haka_Water", "Bottom of the Well Moat Water"},
	{"unset", ""},
	{"En_Ma2", "Adult Malon {Stable & Lon Lon Ranch - Ingo Ousted}"},
	{"En_Bom_Chu", "Bombchu Field Model"},
	{"En_Horse_Game_Check", "?: En_Horse_Game_Check"},
	{"Boss_Tw", "Twinrova"},
	{"En_Rr", "Like Like"},
	{"En_Ba", "Parasitic Tentacle"},
	{"En_Bx", "Tentacle Obstruction"},
	{"En_Anubice", "Anubis"},
	{"En_Anubice_Fire", "Anubis-Killing Fire Trap"},
	{"Bg_Mori_Hashigo", "Forest Temple Dropdown Ladder"},
	{"Bg_Mori_Hashira4", "Forest Temple Rotating Lava Room Platforms"},
	{"Bg_Mori_Idomizu", "Forest Temple Well Path Water"},
	{"Bg_Spot16_Doughnut", "Death Mountain Cloud Ring"},
	{"Bg_Bdan_Switch", "Jabu-Jabu's Belly Switch"},
	{"En_Ma1", "Child Malon"},
	{"Boss_Ganon", "Ganondorf"},
	{"Boss_Sst", "Bongo Bongo"},
	{"unset", ""},
	{"unset", ""},
	{"En_Ny", "Spike Trap"},
	{"En_Fr", "Frog"},
	{"Item_Shield", "Collectible Deku Shield"},
	{"Bg_Ice_Shelter", "Meltable Ice Covering"},
	{"En_Ice_Hono", "Blue Fire"},
	{"Item_Ocarina", "Collectible Ocarina of Time"},
	{"unset", ""},
	{"unset", ""},
	{"Magic_Dark", "Nayru's Love Effect"},
	{"Demo_6K", "Sage Light Orbs"},
	{"En_Anubice_Tag", "Anubis Spawner"},
	{"Bg_Haka_Gate", "?: Bg_Haka_Gate"},
	{"Bg_Spot15_Saku", "Hyrule Castle Gate"},
	{"Bg_Jya_Goroiwa", "Rolling Boulder {Spirit Temple}"},
	{"Bg_Jya_Zurerukabe", "Spirit Temple Shifting Wall"},
	{"unset", ""},
	{"Bg_Jya_Cobra", "Snake Statue"},
	{"Bg_Jya_Kanaami", "Mesh Bridge"},
	{"Fishing", "Fishing Pond & Proprietor"},
	{"Obj_Oshihiki", "Pushblock"},
	{"Bg_Gate_Shutter", "Gate to Death Mountain Trail"},
	{"Eff_Dust", "Dust Particles"},
	{"Bg_Spot01_Fusya", "Kakariko Village Windmill Blades"},
	{"Bg_Spot01_Idohashira", "Kakariko Village Well Crossbeam"},
	{"Bg_Spot01_Idomizu", "Kakariko Village Well Water"},
	{"Bg_Po_Syokudai", "Torch Stand {Poe Sisters}"},
	{"Bg_Ganon_Otyuka", "Ganondorf's Lair Floor Tile"},
	{"Bg_Spot15_Rrbox", "Lon Lon Milk Crate"},
	{"Bg_Umajump", "Horse Jumping Fence"},
	{"unset", ""},
	{"Arrow_Fire", "Collectible Fire Arrows"},
	{"Arrow_Ice", "Collectible Ice Arrows"},
	{"Arrow_Light", "Collectible Light Arrows"},
	{"unset", ""},
	{"unset", ""},
	{"Item_Etcetera", "Collectible Quest Items"},
	{"Obj_Kibako", "Small Wooden Crate"},
	{"Obj_Tsubo", "Pot"},
	{"En_Wonder_Item", "Collectible Field Items {Invisible}"},
	{"En_Ik", "Iron Knuckle {Field Enemy}"},
	{"Demo_Ik", "Iron Knuckle {Cutscenes}"},
	{"En_Skj", "Skullkid"},
	{"En_Skjneedle", "Skullkid's Needle"},
	{"En_G_Switch", "Silver Rupee"},
	{"Demo_Ext", "Kotake & Koume's Portal"},
	{"Demo_Shd", "Bongo Bongo's Shadow"},
	{"En_Dns", "Business Scrub {Surrendered}"},
	{"Elf_Msg", "Navi Message {Automatically Triggered}"},
	{"En_Honotrap", "Flame-Shooting Eye Switch"},
	{"En_Tubo_Trap", "Flying Pot"},
	{"Obj_Ice_Poly", "?: Obj_Ice_Poly"},
	{"Bg_Spot03_Taki", "Zora's River Waterfall"},
	{"Bg_Spot07_Taki", "Zora's Domain Waterfall"},
	{"En_Fz", "Freezard"},
	{"En_Po_Relay", "Dampé's Ghost"},
	{"Bg_Relay_Objects", "Dampé's Relay Objects"},
	{"En_Diving_Game", "Diving Game Zora"},
	{"En_Kusa", "Grass Clump & Regenerating Grass"},
	{"Obj_Bean", "Bean Planting Spot"},
	{"Obj_Bombiwa", "Bombable Boulder"},
	{"unset", ""},
	{"unset", ""},
	{"Obj_Switch", "Bronze / Diamond / Eye Switch"},
	{"Obj_Elevator", "Stone Elevator"},
	{"Obj_Lift", "Deku Tree Elevator"},
	{"Obj_Hsblock", "Hookshot Target Pillar"},
	{"En_Okarina_Tag", "Ocarina Spot"},
	{"En_Yabusame_Mark", "?: En_Yabusame_Mark"},
	{"En_Goroiwa", "Rolling Boulder {Generic}"},
	{"En_Ex_Ruppy", "Deku Target Game Rupee"},
	{"En_Toryo", "Carpenter Boss"},
	{"En_Daiku", "Carpenter {Thieves' Hideout & Carpenters' Tent}"},
	{"unset", ""},
	{"En_Nwc", "Cucco Chick"},
	{"En_Blkobj", "Dark Link's Illusion Room"},
	{"Item_Inbox", "?: Item_Inbox"},
	{"En_Ge1", "Gerudo in White"},
	{"Obj_Blockstop", "?: Obj_Blockstop"},
	{"En_Sda", "Dynamic Shadow"},
	{"En_Clear_Tag", "Arwing"},
	{"En_Niw_Lady", "Cucco Lady"},
	{"En_Gm", "Medigoron"},
	{"En_Ms", "Magic Bean Seller"},
	{"En_Hs", "Carpenter Boss's Son {Lost Woods}"},
	{"Bg_Ingate", "Gate to Ingo's Ranch"},
	{"En_Kanban", "Square Sign"},
	{"En_Heishi3", "Soldier {Hyrule Castle}"},
	{"En_Syateki_Niw", "?: En_Syateki_Niw"},
	{"En_Attack_Niw", "Cucco {Attacking}"},
	{"Bg_Spot01_Idosoko", "Well Stopper"},
	{"En_Sa", "Saria {Gameplay}"},
	{"En_Wonder_Talk", "Checkable Green Navi Spot"},
	{"Bg_Gjyo_Bridge", "Rainbow Bridge"},
	{"En_Ds", "Potion Shop Granny"},
	{"En_Mk", "Lake Scientist"},
	{"En_Bom_Bowl_Man", "Bombchu Bowling Alley Employee"},
	{"En_Bom_Bowl_Pit", "?: En_Bom_Bowl_Pit"},
	{"En_Owl", "Kaepora Gaebora"},
	{"En_Ishi", "Silver Gauntlets Boulder"},
	{"Obj_Hana", "Graveyard Flower / Rock & Grass Pulled by Kokiri"},
	{"Obj_Lightswitch", "Sun Switch"},
	{"Obj_Mure2", "Groups of Rocks & Grass Clumps"},
	{"En_Go", "Generic Goron {Early}"},
	{"En_Fu", "Windmill Man"},
	{"unset", ""},
	{"En_Changer", "Treasure Chest {Treasure Chest Shop}"},
	{"Bg_Jya_Megami", "Goddess Statue"},
	{"Bg_Jya_Lift", "Ceiling Elevator"},
	{"Bg_Jya_Bigmirror", "Ceiling Mirror"},
	{"Bg_Jya_Bombchuiwa", "Bombable Bombchu Boulder"},
	{"Bg_Jya_Amishutter", "Hookshot Grate"},
	{"Bg_Jya_Bombiwa", "?: Bg_Jya_Bombiwa"},
	{"Bg_Spot18_Basket", "Spinning Goron Vase"},
	{"unset", ""},
	{"En_Ganon_Organ", "Ganondorf's Organ"},
	{"En_Siofuki", "Small Water Spout"},
	{"En_Stream", "Big Water Spout"},
	{"unset", ""},
	{"En_Mm", "Running Man {Hyrule Field & Ending}"},
	{"En_Ko", "Kokiri Spawner"},
	{"En_Kz", "King Zora"},
	{"En_Weather_Tag", "Weather-Changing Tag"},
	{"Bg_Sst_Floor", "Bongo Bongo's Drum Head"},
	{"En_Ani", "Man on Kakariko Rooftop"},
	{"En_Ex_Item", "Bombchu Bowling Prizes"},
	{"Bg_Jya_Ironobj", "Iron Knuckle Throne & Columns"},
	{"En_Js", "Carpet Merchant"},
	{"En_Jsjutan", "Carpet Merchant's Magic Carpet"},
	{"En_Cs", "Graveyard Boy"},
	{"En_Md", "Mido"},
	{"En_Hy", "Hylian Spawner"},
	{"En_Ganon_Mant", "Ganondorf's Cape"},
	{"En_Okarina_Effect", "Song of Storms Effect"},
	{"En_Mag", "Title Screen Overlay"},
	{"Door_Gerudo", "Thieves' Hideout Cell Door"},
	{"Elf_Msg2", "Navi Message {Targetable}"},
	{"Demo_Gt", "Ganon's Tower Exterior {Collapsing} Objects"},
	{"En_Po_Field", "Big Poe"},
	{"Efc_Erupc", "Death Mountain Eruption Effects"},
	{"Bg_Zg", "Gate Barring Escape From Ganon's Tower"},
	{"En_Heishi4", "Soldier {Hyrule Castle Town & Kakariko Village}"},
	{"En_Zl3", "Adult Zelda {Normal Gameplay}"},
	{"Boss_Ganon2", "Ganon"},
	{"En_Kakasi", "Pierre {Lake Hylia}"},
	{"En_Takara_Man", "Treasure Chest Shop Proprietor"},
	{"Obj_Makeoshihiki", "Make Pushblock"},
	{"Oceff_Spot", "Sun's Song Effect"},
	{"End_Title", "Ending Overlays"},
	{"unset", ""},
	{"En_Torch", "Grotto Treasure Chest"},
	{"Demo_Ec", "Ending Cutscene NPCs"},
	{"Shot_Sun", "Fire Arrow Trigger & Big Fairy"},
	{"En_Dy_Extra", "Great Fairy's Healing Beam"},
	{"En_Wonder_Talk2", "Checkable Spot"},
	{"En_Ge2", "Patrolling Gerudo in Purple"},
	{"Obj_Roomtimer", "Room Timer"},
	{"En_Ssh", "Skulltula House Resident {Cursed}"},
	{"En_Sth", "Skulltula House Resident {Curse Lifted}"},
	{"Oceff_Wipe", "Lullaby / Song of Time Effect"},
	{"Oceff_Storm", "Song of Storms Effect"},
	{"En_Weiyer", "Stinger {Water}"},
	{"Bg_Spot05_Soko", "Sacred Forest Meadow Pond Bottom"},
	{"Bg_Jya_1flift", "Spirit Temple Entrance Room Elevator"},
	{"Bg_Jya_Haheniron", "Iron Knuckle Debris"},
	{"Bg_Spot12_Gate", "Gate to the Haunted Wasteland"},
	{"Bg_Spot12_Saku", "Gate to the Gerudo Training Ground"},
	{"En_Hintnuts", "Deku Scrub {Inside the Deku Tree}"},
	{"En_Nutsball", "Deku Scrub Projectile"},
	{"Bg_Spot00_Break", "Broken Drawbridge"},
	{"En_Shopnuts", "Business Scrub {Attacking}"},
	{"En_It", "Collectable Grave-Digging Game Items"},
	{"En_GeldB", "Gerudo Fighter"},
	{"Oceff_Wipe2", "Epona's Song Effect"},
	{"Oceff_Wipe3", "Saria's Song Effect"},
	{"En_Niw_Girl", "Cucco-Chasing Girl"},
	{"En_Dog", "Dog"},
	{"En_Si", "Gold Skulltula Token"},
	{"Bg_Spot01_Objects2", "Kakariko Village Objects"},
	{"Obj_Comb", "Beehive"},
	{"Bg_Spot11_Bakudankabe", "Bombable Wall {Desert Colossus}"},
	{"Obj_Kibako2", "Large Wooden Crate"},
	{"En_Dnt_Demo", "Forest Stage Actor Spawner"},
	{"En_Dnt_Jiji", "Forest Stage Judge"},
	{"En_Dnt_Nomal", "Deku Scrub {Deku Target Game}"},
	{"En_Guest", "Happy Mask Shop Customer"},
	{"Bg_Bom_Guard", "Bombchu Bowling Alley Walls"},
	{"En_Hs2", "Carpenter Boss's Son {Kakariko Village}"},
	{"Demo_Kekkai", "Ganon's Castle Barrier"},
	{"Bg_Spot08_Bakudankabe", "Zora's Fountain Bombable Wall"},
	{"Bg_Spot17_Bakudankabe", "Death Mountain Crater Bombable Wall"},
	{"unset", ""},
	{"Obj_Mure3", "Group of Rupees"},
	{"En_Tg", "Honey & Darling"},
	{"En_Mu", "Haggling Shoppers"},
	{"En_Go2", "Generic Goron & Biggoron"},
	{"En_Wf", "Wolfos"},
	{"En_Skb", "Stalchild"},
	{"Demo_Gj", "Ganon's Lair Rubble"},
	{"Demo_Geff", "Ganon's Lair Rubble Fragment"},
	{"Bg_Gnd_Firemeiro", "Fire Trial Sinking Zig-Zag Platform"},
	{"Bg_Gnd_Darkmeiro", "Shadow Trial Invisible Path"},
	{"Bg_Gnd_Soulmeiro", "?: Bg_Gnd_Soulmeiro"},
	{"Bg_Gnd_Nisekabe", "Ganon's Castle Fake Wall"},
	{"Bg_Gnd_Iceblock", "Water Trial Ice Pushblock"},
	{"En_Gb", "Poe Collector"},
	{"En_Gs", "Gossip Stone"},
	{"Bg_Mizu_Bwall", "Water Temple Bombable Wall"},
	{"Bg_Mizu_Shutter", "Water Temple Gate"},
	{"En_Daiku_Kakariko", "Kakariko Village - Carpenter"},
	{"Bg_Bowl_Wall", "Bombchu Bowling Alley Walls"},
	{"En_Wall_Tubo", "?: En_Wall_Tubo"},
	{"En_Po_Desert", "Poe Guide"},
	{"En_Crow", "Guay"},
	{"Door_Killer", "Door Mimic"},
	{"Bg_Spot11_Oasis", "Oasis Water"},
	{"Bg_Spot18_Futa", "Spinning Goron Vase Lid"},
	{"Bg_Spot18_Shutter", "Door to Darunia's Room"},
	{"En_Ma3", "Adult Malon {Day}"},
	{"En_Cow", "Cow"},
	{"Bg_Ice_Turara", "Icicle"},
	{"Bg_Ice_Shutter", "Ice Cavern Bars"},
	{"En_Kakasi2", "Pierre {Wandering}"},
	{"En_Kakasi3", "Bonooru"},
	{"Oceff_Wipe4", "Scarecrow's Song Effect"},
	{"En_Eg", "?: En_Eg"},
	{"Bg_Menkuri_Nisekabe", "Gerudo Training Ground Fake Wall"},
	{"En_Zo", "Zora"},
	{"Obj_Makekinsuta", "Gold Skulltula Spawner"},
	{"En_Ge3", "Nabooru's Second-in-Command"},
	{"Obj_Timeblock", "Time Block"},
	{"Obj_Hamishi", "Breakable Bronze Boulder"},
	{"En_Zl4", "Child Zelda {Gameplay & Cutscene 04}"},
	{"En_Mm2", "Running Man {Carpenters' Tent & Race}"},
	{"Bg_Jya_Block", "Silver Gauntlets Pushblock {?}"},
	{"Obj_Warp2block", "Time Block"},
	{"Bg_Ydan_*", "Deku Tree vertical web wall on top floor"},
	{"Boss_Ganon*", "?: Boss_Ganon*"},
	{"En_Hintstone", "Sheikah Stone"},
	{"Bg_Mizu_*", "?: Bg_Mizu_*"}
};